### ISSUE TITLE
Environment variable to control anonymous access

### ISSUE THREAD

**Issue by EnriqueHernandezL** [arkmq-org/arkmq-org-broker-image#20]
https://github.com/artemiscloud/activemq-artemis-broker-image/blob/7f4a887adaa720e61281a143cf3839227cc758e0/modules/activemq-artemis-install/added/launch.sh#L16

Instead of the hard coded "--allow-anonymous", I would expect the launch.sh script to decide between that and "--require-login", depending on some environment variable (e.g. ALLOW_ANONYMOUS=true/false).

**Comment by brusdev** [comment]
@EnriqueHernandezL the [artemiscloud/activemq-artemis-broker-image](https://github.com/artemiscloud/activemq-artemis-broker-image) is a very basic container image. You could pass your custom configuration mounting a volume with the broker instance files otherwise you could use [artemiscloud/activemq-artemis-broker-kubernetes-image](https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image) that includes a better [launch script](https://github.com/artemiscloud/activemq-artemis-broker-kubernetes-image/blob/main/modules/activemq-artemis-launch/added/launch.sh#L62) with `AMQ_REQUIRE_LOGIN` environment variable to configure the user authentication.

**Comment by tlbueno** [comment]
I am closing this issue based on @brusdev reply above.
